name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - test-deploy-gh-page

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Email
        run: git config --global user.email "EvheniyY@planit-inc.com"

      - name: Name
        run: git config --global user.name "planit-evy"

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy Storybook
        run: npm run deploy-storybook
